# Generated by Django 2.2.6 on 2019-11-04 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_country', models.CharField(max_length=512)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=512, verbose_name='name')),
                ('item_category', models.CharField(max_length=512, verbose_name='category')),
                ('item_price', models.IntegerField(verbose_name='price')),
                ('item_date', models.DateField(auto_now_add=True)),
                ('item_pic', models.ImageField(upload_to='media/', verbose_name="item's Picture")),
                ('item_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybay_app.Profile', verbose_name='user')),
            ],
            options={
                'verbose_name': 'item List',
                'verbose_name_plural': 'item List',
            },
        ),
    ]
