# Generated by Django 2.2.6 on 2019-11-03 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=512, unique=True)),
                ('user_pass', models.CharField(max_length=512)),
                ('user_country', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'app_user',
            },
        ),
        migrations.CreateModel(
            name='AppItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=512)),
                ('item_category', models.CharField(max_length=512)),
                ('item_price', models.IntegerField()),
                ('item_date', models.DateField()),
                ('item_pic', models.BinaryField()),
                ('item_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybay_app.AppUser')),
            ],
            options={
                'db_table': 'app_item',
            },
        ),
    ]
