# Generated by Django 2.2.6 on 2019-11-09 16:14

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mybay_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='itemedit',
            name='item_country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
