# Generated by Django 2.2.6 on 2019-11-03 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybay_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name': 'User List'},
        ),
    ]
