# Generated by Django 2.2.6 on 2019-11-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybay_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_pic',
            field=models.ImageField(upload_to='images/', verbose_name="item's Picture"),
        ),
    ]
