# Generated by Django 2.2.6 on 2019-11-03 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybay_app', '0002_auto_20191103_0321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appitem',
            options={'verbose_name': 'item List', 'verbose_name_plural': 'item List'},
        ),
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name': 'user List', 'verbose_name_plural': 'user List'},
        ),
        migrations.AlterField(
            model_name='appitem',
            name='item_category',
            field=models.CharField(max_length=512, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='appitem',
            name='item_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appitem',
            name='item_name',
            field=models.CharField(max_length=512, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='appitem',
            name='item_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybay_app.AppUser', verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='appitem',
            name='item_pic',
            field=models.BinaryField(verbose_name="item's Picture"),
        ),
        migrations.AlterField(
            model_name='appitem',
            name='item_price',
            field=models.IntegerField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='user_country',
            field=models.CharField(max_length=512, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='user_email',
            field=models.CharField(max_length=512, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='user_pass',
            field=models.CharField(max_length=512, verbose_name='password'),
        ),
    ]
