# Generated by Django 2.2.6 on 2019-11-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybay_app', '0002_auto_20191105_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.FloatField(verbose_name='price'),
        ),
    ]
