# Generated by Django 2.2.6 on 2019-11-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybay_app', '0003_auto_20191105_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_pic',
            field=models.ImageField(upload_to='images', verbose_name="item's Picture"),
        ),
    ]
