# Generated by Django 2.2.6 on 2019-11-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybay_app', '0003_auto_20191103_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appitem',
            name='item_pic',
            field=models.ImageField(upload_to='media/', verbose_name="item's Picture"),
        ),
    ]
