# Generated by Django 2.2.6 on 2019-11-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybay_app', '0004_auto_20191103_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='user_email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
    ]
